##########
### NB: the paths in this YAML config are relative to the root of the Wraith directory,
### as `bundle exec rspec` is run from the root.
##########

#Headless browser option
browser: "casperjs"
snap_file: "spec/js/custom_snap_file.js"

# Type the name of the directory that shots will be stored in
directory: 'shots'

# Add only 2 domains, key will act as a label
domains:
  afrique: "http://www.bbc.com/afrique"
  russian: "http://www.bbc.com/russian"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  uk_index: /uk

#Amount of fuzz ImageMagick will use
fuzz: '20%'

# Number of threads used when saving images
threads: 7
